---
# Source: ingress-nginx/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    helm.sh/chart: ingress-nginx-3.30.0
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: interview
    app.kubernetes.io/version: "0.46.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: interview-ingress-nginx-controller
spec:
  type: LoadBalancer
  loadBalancerIP: 34.152.21.254
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: interview
    app.kubernetes.io/component: controller
