---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress
resources:
- namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- controller-configmap.yaml
- controller-deployment.yaml
- controller-role.yaml
- controller-rolebinding.yaml
- controller-service-webhook.yaml
- controller-service.yaml
- controller-serviceaccount.yaml
